export const LOADING_STATES = {
  INITIAL: "INITIAL",
  PENDING: "PENDING",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
} as const;

export type LoadingStates = keyof typeof LOADING_STATES;

export const CUSTOM_EVENTS = {
  UPDATE_BIBLE_TRANSLATION: "UPDATE_BIBLE_TRANSLATION",
  UPDATE_BIBLE_VERSE: "UPDATE_BIBLE_VERSE",
  UPDATE_RECITED_BIBLE_VERSE: "UPDATE_RECITED_BIBLE_VERSE",
  NAVIGATE_TO_PAGE: "NAVIGATE_TO_PAGE",
  SEARCH_FOR_BIBLE_VERSE: "SEARCH_FOR_BIBLE_VERSE",
} as const;

export type CustomEvents = keyof typeof CUSTOM_EVENTS;

export const MEMORIZE_BIBLE_VERSES_API_BASE_URL =
  import.meta.env.VITE_MEMORIZE_BIBLE_VERSES_API_BASE_URL ??
  "https://memorize-bible-verses-api-server.fly.dev";
